### ISSUE TITLE
Update network configuration to include Token dApp URL

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/networks#77]
For mainnet

```toml
[TokenDApp]
  URL = "token.vega.xyz"
  LocalPort = 1848
```

For fairground
```toml
[TokenDApp]
  URL = "token.fairground.wtf"
  LocalPort = 1848
```
